services:
  app:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}  # Берет из .env или использует 1000
        GROUP_ID: ${GROUP_ID:-1000}
    image: php83-composer
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    ports:
       - "9000:9000"  # Порт FPM

  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

#  nginx:
#    image: nginx:alpine
#    ports:
#      - "443:443"
#      - "80:80"
#    volumes:
#      - ./etc/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#      - ./storage/app/certs:/etc/nginx/certs
#    depends_on:
#      - app

  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./etc/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./src:/var/www
      - caddy_data:/data
    depends_on:
      - app

volumes:
  pg_data:
  caddy_data:
